#!/usr/bin/env python3
"""
Raid: Shadow Legends — Siege Scroll Tracker
=============================================
All-in-one GUI with automatic setup detection.
No Proxifier needed — uses hosts file redirect + reverse proxy.

Requirements:
    mitmproxy installed and on PATH
    mitmproxy CA certificate trusted in Windows
    Run as Administrator
"""

import os
import sys
import glob
import json
import socket
import subprocess
import threading
import time
import ctypes
from datetime import datetime
from collections import defaultdict

import msgpack

import tkinter as tk
from tkinter import ttk, messagebox

# ── Paths ────────────────────────────────────────────────────────────────────

SCRIPT_DIR = os.path.dirname(os.path.abspath(sys.argv[0]))
ADDON_PATH = os.path.join(SCRIPT_DIR, "siege_addon.py")
SAVE_DIR = os.path.join(SCRIPT_DIR, "siege_data")
ALLIANCE_FILE = os.path.join(SAVE_DIR, "alliance_data.bin")
CONFIG_FILE = os.path.join(SCRIPT_DIR, "config.json")
HOSTS_PATH = r"C:\Windows\System32\drivers\etc\hosts"
HOSTS_MARKER = "# SiegeTracker"
MITMPROXY_CERT = os.path.join(os.path.expanduser("~"), ".mitmproxy", "mitmproxy-ca-cert.cer")

# ── Embedded Addon ───────────────────────────────────────────────────────────
# siege_addon.py is loaded by mitmdump (separate process), so it must exist
# as a file on disk. We embed it here and auto-extract if missing.

ADDON_SOURCE = '''\
"""
Raid: Shadow Legends - Siege Auto-Save Addon for mitmproxy
Auto-generated by SiegeTracker. Do not move or rename.
"""

import os
import time
import hashlib
from mitmproxy import http, ctx

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SAVE_DIR = os.path.join(SCRIPT_DIR, "siege_data")
CAPTURE_METHODS = {"Siege.GetBuilding", "Alliance.Get"}


class SiegeAddon:
    def __init__(self):
        self.building_count = 0
        self.alliance_captured = False
        self.seen_hashes = set()
        os.makedirs(SAVE_DIR, exist_ok=True)

        old_files = [
            f for f in os.listdir(SAVE_DIR)
            if f.startswith("building_") and f.endswith(".bin")
        ]
        if old_files:
            for f in old_files:
                os.remove(os.path.join(SAVE_DIR, f))
            ctx.log.info(f"[Siege] Cleared {len(old_files)} old building files.")

        if os.path.exists(os.path.join(SAVE_DIR, "alliance_data.bin")):
            ctx.log.info("[Siege] Existing clan roster found.")

        ctx.log.info(f"[Siege] Addon loaded. Saving to: {SAVE_DIR}")
        ctx.log.info("[Siege] Log in to capture roster, then click buildings.")

    def response(self, flow: http.HTTPFlow):
        method = flow.request.headers.get("server-method", "")
        if method not in CAPTURE_METHODS:
            return
        if not flow.response or not flow.response.content:
            return
        if method == "Alliance.Get":
            self._save_alliance(flow)
        elif method == "Siege.GetBuilding":
            self._save_building(flow)

    def _save_alliance(self, flow):
        fpath = os.path.join(SAVE_DIR, "alliance_data.bin")
        with open(fpath, "wb") as f:
            f.write(flow.response.content)
        size_kb = len(flow.response.content) / 1024
        self.alliance_captured = True
        ctx.log.info(f"[Siege] Clan roster captured! ({size_kb:.1f} KB)")

    def _save_building(self, flow):
        content_hash = hashlib.md5(flow.response.content).hexdigest()
        if content_hash in self.seen_hashes:
            ctx.log.info("[Siege] Skipped duplicate building response")
            return
        self.seen_hashes.add(content_hash)

        self.building_count += 1
        timestamp = time.strftime("%H%M%S")
        fname = f"building_{timestamp}_{self.building_count:03d}.bin"
        fpath = os.path.join(SAVE_DIR, fname)

        with open(fpath, "wb") as f:
            f.write(flow.response.content)

        size_kb = len(flow.response.content) / 1024
        ctx.log.info(
            f"[Siege] Saved building #{self.building_count} "
            f"({size_kb:.1f} KB) -> {fname}"
        )

        if not self.alliance_captured:
            if not os.path.exists(os.path.join(SAVE_DIR, "alliance_data.bin")):
                ctx.log.warn("[Siege] No clan roster yet! Relog to capture it.")


addons = [SiegeAddon()]
'''


def ensure_addon_exists():
    """Write siege_addon.py to disk if it doesn't exist."""
    if not os.path.exists(ADDON_PATH):
        try:
            with open(ADDON_PATH, "w", encoding="utf-8") as f:
                f.write(ADDON_SOURCE)
            return True
        except Exception:
            return False
    return True

# ── Config ───────────────────────────────────────────────────────────────────

DEFAULT_CONFIG = {"server_domain": "rdint1s09.plrm.zone"}


def load_config():
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE) as f:
                return {**DEFAULT_CONFIG, **json.load(f)}
        except Exception:
            pass
    return dict(DEFAULT_CONFIG)


def save_config(cfg):
    try:
        with open(CONFIG_FILE, "w") as f:
            json.dump(cfg, f, indent=2)
    except Exception:
        pass


# ── System Checks ────────────────────────────────────────────────────────────

def is_admin():
    try:
        return ctypes.windll.shell32.IsUserAnAdmin() != 0
    except Exception:
        return False


def relaunch_as_admin():
    try:
        ctypes.windll.shell32.ShellExecuteW(
            None, "runas", sys.executable,
            f'"{os.path.abspath(sys.argv[0])}"', None, 1)
    except Exception:
        pass
    sys.exit(0)


def check_mitmdump():
    """Check if mitmdump is available on PATH."""
    try:
        r = subprocess.run(["mitmdump", "--version"],
                          capture_output=True, timeout=5,
                          creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
        return r.returncode == 0
    except Exception:
        return False


def check_cert_file_exists():
    """Check if mitmproxy has generated its CA cert."""
    return os.path.exists(MITMPROXY_CERT)


def generate_cert():
    """Run mitmdump briefly to generate the CA cert files."""
    try:
        p = subprocess.Popen(
            ["mitmdump", "--listen-port", "18999"],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
        time.sleep(2)
        p.terminate()
        p.wait(timeout=5)
    except Exception:
        pass
    return os.path.exists(MITMPROXY_CERT)


def check_cert_installed():
    """Check if mitmproxy CA cert is installed in Windows trust store."""
    try:
        r = subprocess.run(
            ["certutil", "-verifystore", "Root", "mitmproxy"],
            capture_output=True, timeout=10,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
        return r.returncode == 0
    except Exception:
        return False


def install_cert():
    """Install mitmproxy CA cert into Windows Trusted Root store."""
    if not os.path.exists(MITMPROXY_CERT):
        return False
    try:
        r = subprocess.run(
            ["certutil", "-addstore", "Root", MITMPROXY_CERT],
            capture_output=True, timeout=10,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
        return r.returncode == 0
    except Exception:
        return False


# ── Hosts File Management ───────────────────────────────────────────────────

def add_hosts_entry(domain):
    entry = f"127.0.0.1  {domain}  {HOSTS_MARKER}\n"
    try:
        with open(HOSTS_PATH, "r") as f:
            content = f.read()
        if HOSTS_MARKER in content:
            return True
        with open(HOSTS_PATH, "a") as f:
            f.write(entry)
        return True
    except Exception:
        return False


def remove_hosts_entry():
    try:
        with open(HOSTS_PATH, "r") as f:
            lines = f.readlines()
        new_lines = [l for l in lines if HOSTS_MARKER not in l]
        with open(HOSTS_PATH, "w") as f:
            f.writelines(new_lines)
        return True
    except Exception:
        return False


# ── Alliance / Roster Parsing ────────────────────────────────────────────────

def parse_alliance_data(filepath):
    try:
        with open(filepath, "rb") as f:
            data = msgpack.unpackb(f.read(), raw=False, strict_map_key=False)
    except Exception:
        return {}

    members = {}
    if isinstance(data, dict) and "u" in data and isinstance(data["u"], list):
        for profile in data["u"]:
            if isinstance(profile, dict) and "i" in profile and "n" in profile:
                uid = profile["i"]
                name = profile["n"]
                if isinstance(uid, int) and isinstance(name, str) and len(name) > 0:
                    members[str(uid)] = name
    return members


# ── Building Parsing ────────────────────────────────────────────────────────

def building_name_from_id(bid):
    if bid == 1:
        return "Stronghold"
    elif 100 <= bid < 200:
        return f"DefenseTower{bid - 99}"
    elif 1000 <= bid < 2000:
        return f"MagicTower{bid - 1000}"
    elif 2000 <= bid < 3000:
        return f"ManaShrine{bid - 2000}"
    elif 3000 <= bid < 4000:
        return f"Post{bid - 3000}"
    return f"Building{bid}"


def find_attacks_recursive(obj, entries, bname, clan_members):
    if isinstance(obj, dict):
        if ("a" in obj and isinstance(obj["a"], dict) and "i" in obj["a"]
                and "w" in obj and isinstance(obj["w"], bool)):
            uid = str(obj["a"]["i"])
            if uid in clan_members:
                entries.append({"uid": uid, "name": clan_members[uid],
                                "building": bname, "won": obj["w"]})
            return
        for v in obj.values():
            find_attacks_recursive(v, entries, bname, clan_members)
    elif isinstance(obj, list):
        for item in obj:
            find_attacks_recursive(item, entries, bname, clan_members)


def parse_bin_file(filepath, clan_members):
    with open(filepath, "rb") as f:
        data = msgpack.unpackb(f.read(), raw=False, strict_map_key=False)
    bid = 0
    if isinstance(data, dict) and "b" in data and isinstance(data["b"], dict):
        bid = data["b"].get("i", 0)
    bname = building_name_from_id(bid)
    entries = []
    find_attacks_recursive(data, entries, bname, clan_members)
    return entries, bname, bid


def parse_all_buildings(search_dir, clan_members):
    bin_files = sorted(glob.glob(os.path.join(search_dir, "building_*.bin")))
    bin_files = [f for f in bin_files if not f.endswith("_req.bin")]

    all_entries, buildings, seen_ids = [], [], set()
    for fpath in bin_files:
        try:
            entries, bname, bid = parse_bin_file(fpath, clan_members)
            if bid in seen_ids:
                continue
            seen_ids.add(bid)
            all_entries.extend(entries)
            buildings.append(bname)
        except Exception:
            pass

    stats = {}
    for uid, name in clan_members.items():
        stats[uid] = {"name": name, "scrolls": 0, "wins": 0,
                       "losses": 0, "buildings": set()}
    for entry in all_entries:
        uid = entry["uid"]
        if uid not in stats:
            stats[uid] = {"name": entry["name"], "scrolls": 0,
                           "wins": 0, "losses": 0, "buildings": set()}
        stats[uid]["scrolls"] += 1
        if entry["won"]:
            stats[uid]["wins"] += 1
        else:
            stats[uid]["losses"] += 1
        stats[uid]["buildings"].add(entry["building"])

    bldg_counts = defaultdict(lambda: [0, 0])
    for e in all_entries:
        bldg_counts[e["building"]][0] += 1
        if e["won"]:
            bldg_counts[e["building"]][1] += 1

    return stats, buildings, bldg_counts


# ── GUI Application ──────────────────────────────────────────────────────────

class SiegeTrackerApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Siege Scroll Tracker")
        self.root.geometry("850x750")
        self.root.minsize(700, 500)
        self.root.configure(bg="#1a1a2e")

        # Set window icon
        ico_path = os.path.join(SCRIPT_DIR, "siege_tracker.ico")
        if os.path.exists(ico_path):
            try:
                self.root.iconbitmap(ico_path)
            except Exception:
                pass

        self.mitm_process = None
        self.monitoring = False
        self.file_count = 0
        self.clan_members = {}
        self.config = load_config()
        self.server_ip = None
        self._detecting = False
        self.report_plain = ""

        self.bg = "#1a1a2e"
        self.bg_light = "#16213e"
        self.accent = "#0f3460"
        self.highlight = "#e94560"
        self.text_color = "#eee"
        self.text_dim = "#8899aa"
        self.green = "#4ecca3"
        self.red = "#e94560"
        self.yellow = "#f0c040"

        self._setup_styles()
        self._build_ui()
        self._load_roster()

        # Auto-extract addon if missing
        ensure_addon_exists()

        # Run setup check after UI is built
        self.root.after(100, self._run_setup_check)

    def _setup_styles(self):
        s = ttk.Style()
        s.theme_use("clam")
        s.configure("Main.TFrame", background=self.bg)
        s.configure("Accent.TButton", background=self.accent,
            foreground="white", font=("Segoe UI", 11, "bold"), padding=(20, 10))
        s.map("Accent.TButton",
            background=[("active", self.highlight), ("disabled", "#333")])
        s.configure("Stop.TButton", background=self.highlight,
            foreground="white", font=("Segoe UI", 11, "bold"), padding=(20, 10))
        s.configure("Small.TButton", background=self.accent,
            foreground="white", font=("Segoe UI", 9), padding=(10, 5))
        s.configure("Setup.TButton", background="#2d6a4f",
            foreground="white", font=("Segoe UI", 9, "bold"), padding=(10, 5))
        s.map("Setup.TButton", background=[("active", self.green)])
        s.configure("Header.TLabel", background=self.bg,
            foreground=self.text_color, font=("Segoe UI", 16, "bold"))
        s.configure("Status.TLabel", background=self.bg,
            foreground=self.text_dim, font=("Segoe UI", 10))
        s.configure("Roster.TLabel", background=self.bg,
            foreground=self.text_dim, font=("Segoe UI", 9))
        s.configure("Count.TLabel", background=self.bg,
            foreground=self.green, font=("Segoe UI", 28, "bold"))

    def _build_ui(self):
        main = ttk.Frame(self.root, style="Main.TFrame")
        main.pack(fill="both", expand=True, padx=15, pady=10)

        # Header
        ttk.Label(main, text="Siege Scroll Tracker",
                  style="Header.TLabel").pack(fill="x", pady=(0, 5))

        # Setup status bar
        setup_frame = ttk.Frame(main, style="Main.TFrame")
        setup_frame.pack(fill="x", pady=(0, 3))

        self.setup_labels = {}
        for key, label in [("admin", "Admin"), ("mitmdump", "mitmproxy"),
                           ("cert", "Certificate"), ("addon", "Addon")]:
            f = ttk.Frame(setup_frame, style="Main.TFrame")
            f.pack(side="left", padx=(0, 15))
            lbl = ttk.Label(f, text=f"{label}: ...", style="Roster.TLabel")
            lbl.pack(side="left")
            self.setup_labels[key] = lbl

        self.fix_btn = ttk.Button(setup_frame, text="Fix Issues",
            style="Setup.TButton", command=self._fix_issues)
        self.fix_btn.pack(side="right")
        self.fix_btn.pack_forget()  # Hidden until needed

        # Server config
        server_frame = ttk.Frame(main, style="Main.TFrame")
        server_frame.pack(fill="x", pady=(5, 3))
        ttk.Label(server_frame, text="Game Server:",
                  style="Roster.TLabel").pack(side="left")
        self.server_var = tk.StringVar(value=self.config["server_domain"])
        self.server_entry = tk.Entry(server_frame, textvariable=self.server_var,
            bg=self.bg_light, fg=self.text_color, insertbackground="white",
            font=("Consolas", 10), relief="flat", width=30)
        self.server_entry.pack(side="left", padx=(5, 0))

        self.detect_btn = ttk.Button(server_frame, text="Detect",
            style="Small.TButton", command=self._detect_server)
        self.detect_btn.pack(side="left", padx=(5, 0))

        # Roster status
        self.roster_label = ttk.Label(main, text="", style="Roster.TLabel")
        self.roster_label.pack(fill="x", pady=(3, 5), anchor="w")

        # Capture controls
        capture_frame = ttk.Frame(main, style="Main.TFrame")
        capture_frame.pack(fill="x", pady=(0, 10))

        left_cap = ttk.Frame(capture_frame, style="Main.TFrame")
        left_cap.pack(side="left", fill="x", expand=True)
        self.status_label = ttk.Label(left_cap,
            text="Ready — click Start Capture to begin",
            style="Status.TLabel")
        self.status_label.pack(anchor="w")
        self.count_label = ttk.Label(left_cap, text="", style="Count.TLabel")
        self.count_label.pack(anchor="w")

        btn_frame = ttk.Frame(capture_frame, style="Main.TFrame")
        btn_frame.pack(side="right")
        self.start_btn = ttk.Button(btn_frame, text="▶  Start Capture",
            style="Accent.TButton", command=self._start_capture)
        self.start_btn.pack(pady=(0, 5))
        self.stop_btn = ttk.Button(btn_frame, text="■  Stop & Report",
            style="Stop.TButton", command=self._stop_and_report, state="disabled")
        self.stop_btn.pack()

        # Separator
        tk.Frame(main, height=1, bg=self.accent).pack(fill="x", pady=10)

        # Results header
        results_header = ttk.Frame(main, style="Main.TFrame")
        results_header.pack(fill="x")
        ttk.Label(results_header, text="Report",
                  style="Header.TLabel").pack(side="left")
        self.copy_btn = ttk.Button(results_header, text="Copy to Clipboard",
            style="Small.TButton", command=self._copy_report, state="disabled")
        self.copy_btn.pack(side="right", padx=(0, 5))
        self.report_btn = ttk.Button(results_header,
            text="Generate from existing data",
            style="Small.TButton", command=self._generate_report)
        self.report_btn.pack(side="right", padx=(0, 5))

        # Report text area
        text_frame = ttk.Frame(main, style="Main.TFrame")
        text_frame.pack(fill="both", expand=True, pady=(10, 0))
        self.report_text = tk.Text(text_frame, bg="#0d1117", fg=self.text_color,
            font=("Consolas", 10), insertbackground="white",
            selectbackground=self.accent, relief="flat",
            padx=15, pady=10, wrap="none", state="disabled")
        sy = ttk.Scrollbar(text_frame, command=self.report_text.yview)
        sx = ttk.Scrollbar(text_frame, orient="horizontal",
                           command=self.report_text.xview)
        self.report_text.configure(yscrollcommand=sy.set, xscrollcommand=sx.set)
        sy.pack(side="right", fill="y")
        sx.pack(side="bottom", fill="x")
        self.report_text.pack(fill="both", expand=True)

        for tag, color, font in [
            ("title", self.green, ("Consolas", 11, "bold")),
            ("header", self.yellow, ("Consolas", 10, "bold")),
            ("inactive", self.red, None),
            ("active", self.green, None),
            ("dim", self.text_dim, None),
        ]:
            kw = {"foreground": color}
            if font:
                kw["font"] = font
            self.report_text.tag_configure(tag, **kw)

    # ── Setup Checks ─────────────────────────────────────────────────────

    def _run_setup_check(self):
        """Check all requirements and update status indicators."""
        checks = {}

        # Admin
        checks["admin"] = is_admin()
        self._update_check("admin", "Admin", checks["admin"])

        # mitmdump
        checks["mitmdump"] = check_mitmdump()
        self._update_check("mitmdump", "mitmproxy", checks["mitmdump"])

        # Certificate
        cert_installed = check_cert_installed()
        if cert_installed:
            checks["cert"] = True
        elif check_cert_file_exists():
            checks["cert"] = False  # Exists but not installed
        else:
            checks["cert"] = False
        self._update_check("cert", "Certificate", checks["cert"])

        # Addon file
        checks["addon"] = os.path.exists(ADDON_PATH)
        self._update_check("addon", "Addon", checks["addon"])

        # Show fix button if issues
        has_issues = not all(checks.values())
        if has_issues:
            self.fix_btn.pack(side="right")
            if not checks["mitmdump"]:
                self._set_status("Setup needed — install mitmproxy first", self.yellow)
            elif not checks["cert"]:
                self._set_status("Setup needed — click Fix Issues to install certificate", self.yellow)
            elif not checks["admin"]:
                self._set_status("Not running as Admin — restart with admin rights", self.yellow)
        else:
            self.fix_btn.pack_forget()
            self._set_status("Ready — click Start Capture to begin", self.text_dim)

        # Enable/disable start button
        can_start = checks["admin"] and checks["mitmdump"] and checks["cert"] and checks["addon"]
        self.start_btn.configure(state="normal" if can_start else "disabled")

    def _update_check(self, key, label, ok):
        color = self.green if ok else self.red
        icon = "✓" if ok else "✗"
        self.setup_labels[key].configure(
            text=f"{icon} {label}", foreground=color)

    def _fix_issues(self):
        """Attempt to fix setup issues automatically."""
        messages = []

        if not check_mitmdump():
            messages.append(
                "mitmproxy is not installed.\n\n"
                "Download and install from:\n"
                "https://mitmproxy.org/\n\n"
                "After installing, restart this application."
            )
            messagebox.showinfo("Install mitmproxy", messages[0])
            return

        if not check_cert_file_exists():
            self._set_status("Generating mitmproxy certificate...", self.yellow)
            self.root.update()
            generate_cert()

        if check_cert_file_exists() and not check_cert_installed():
            answer = messagebox.askyesno(
                "Install Certificate",
                "mitmproxy's CA certificate needs to be trusted by Windows\n"
                "so the tool can read game traffic.\n\n"
                "This is safe — it only allows this tool to inspect\n"
                "Raid's connection. Install the certificate now?\n\n"
                f"Certificate: {MITMPROXY_CERT}")
            if answer:
                self._set_status("Installing certificate...", self.yellow)
                self.root.update()
                if install_cert():
                    messagebox.showinfo("Success",
                        "Certificate installed successfully!")
                else:
                    messagebox.showerror("Failed",
                        "Could not install certificate.\n"
                        "Make sure you're running as Administrator.")

        if not is_admin():
            answer = messagebox.askyesno("Admin Required",
                "This app needs administrator privileges.\n"
                "Restart with admin rights?")
            if answer:
                relaunch_as_admin()

        if not os.path.exists(ADDON_PATH):
            ensure_addon_exists()
            if not os.path.exists(ADDON_PATH):
                messagebox.showerror("Missing Addon",
                    f"Could not create siege_addon.py at:\n{ADDON_PATH}\n\n"
                    "Check folder write permissions.")

        self._run_setup_check()

    # ── Roster ───────────────────────────────────────────────────────────

    def _load_roster(self):
        if os.path.exists(ALLIANCE_FILE):
            roster = parse_alliance_data(ALLIANCE_FILE)
            if roster:
                self.clan_members = roster
                self.roster_label.configure(
                    text=f"Clan roster: {len(roster)} members (auto-detected)",
                    foreground=self.green)
                return
        self.roster_label.configure(
            text="No clan roster — log into the game with capture running",
            foreground=self.yellow)

    # ── Status Helpers ───────────────────────────────────────────────────

    def _set_status(self, text, color=None):
        self.status_label.configure(text=text, foreground=color or self.text_dim)

    def _set_count(self, n):
        self.count_label.configure(
            text=f"{n} buildings captured" if n > 0 else "")

    def _write_report(self, text):
        self.report_text.configure(state="normal")
        self.report_text.delete("1.0", "end")
        self.report_text.insert("end", text)
        self.report_text.configure(state="disabled")
        self.report_plain = text

    # ── Server Detection ────────────────────────────────────────────────

    def _detect_server(self):
        """Auto-detect game server by monitoring DNS cache."""
        self.detect_btn.configure(state="disabled")
        self._set_status("Flushing DNS cache...", self.yellow)
        self.root.update()

        # Flush DNS so we get a clean slate
        subprocess.run(["ipconfig", "/flushdns"], capture_output=True,
                       creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
        time.sleep(0.3)

        self._set_status(
            "● Detecting — launch Raid now and wait for login screen...",
            self.yellow)
        self._detecting = True

        threading.Thread(target=self._poll_dns, daemon=True).start()

    def _poll_dns(self):
        """Poll DNS cache for rdint*.plrm.zone entries."""
        import re
        start = time.time()
        timeout = 120  # 2 minutes

        while self._detecting and (time.time() - start) < timeout:
            try:
                r = subprocess.run(
                    ["ipconfig", "/displaydns"],
                    capture_output=True, text=True, timeout=10,
                    creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))

                # Find all rdint domains in DNS cache
                domains = re.findall(
                    r'(rdint\d+s\d+\.plrm\.zone)', r.stdout)

                if domains:
                    # First one to appear after flush is the login server
                    domain = domains[0]
                    self._detecting = False
                    self.root.after(0, self._on_server_detected, domain)
                    return

            except Exception:
                pass

            time.sleep(1)

        # Timeout
        self._detecting = False
        self.root.after(0, self._on_detect_timeout)

    def _on_server_detected(self, domain):
        """Called when server domain is found."""
        self.server_var.set(domain)
        self.config["server_domain"] = domain
        save_config(self.config)
        self.detect_btn.configure(state="normal")
        self._set_status(f"Detected server: {domain}", self.green)

    def _on_detect_timeout(self):
        """Called when detection times out."""
        self.detect_btn.configure(state="normal")
        self._set_status(
            "Detection timed out — enter server manually or try again",
            self.red)

    # ── Capture Control ──────────────────────────────────────────────────

    def _start_capture(self):
        # Stop any active server detection
        self._detecting = False

        domain = self.server_var.get().strip()
        if not domain:
            messagebox.showerror("No Server", "Enter the game server domain.")
            return

        self.config["server_domain"] = domain
        save_config(self.config)

        self._set_status("Resolving server IP...", self.yellow)
        self.start_btn.configure(state="disabled")
        self.root.update()

        # Resolve real IP
        remove_hosts_entry()
        time.sleep(0.2)
        subprocess.run(["ipconfig", "/flushdns"], capture_output=True,
                       creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
        time.sleep(0.3)

        try:
            self.server_ip = socket.gethostbyname(domain)
        except Exception:
            self._set_status("Failed to resolve server IP", self.red)
            self.start_btn.configure(state="normal")
            return

        if not add_hosts_entry(domain):
            self._set_status("Failed to modify hosts file", self.red)
            self.start_btn.configure(state="normal")
            return

        subprocess.run(["ipconfig", "/flushdns"], capture_output=True,
                       creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))

        os.makedirs(SAVE_DIR, exist_ok=True)

        try:
            self.mitm_process = subprocess.Popen(
                ["mitmdump",
                 "--mode", f"reverse:https://{self.server_ip}",
                 "--listen-port", "443",
                 "-s", ADDON_PATH,
                 "--set", "keep_host_header=true",
                 "--quiet"],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
        except FileNotFoundError:
            remove_hosts_entry()
            messagebox.showerror("Error", "mitmdump not found on PATH.")
            self.start_btn.configure(state="normal")
            return

        self.monitoring = True
        self.file_count = 0
        self._set_status(
            f"● Capturing — {domain} → {self.server_ip}", self.green)
        self._set_count(0)
        self.stop_btn.configure(state="normal")
        self.server_entry.configure(state="disabled")
        self.detect_btn.configure(state="disabled")

        threading.Thread(target=self._monitor_files, daemon=True).start()

    def _monitor_files(self):
        prev_alliance = os.path.exists(ALLIANCE_FILE)
        while self.monitoring:
            bins = [f for f in glob.glob(os.path.join(SAVE_DIR, "building_*.bin"))
                    if not f.endswith("_req.bin")]
            count = len(bins)
            if count != self.file_count:
                self.file_count = count
                self.root.after(0, self._set_count, count)
            if not prev_alliance and os.path.exists(ALLIANCE_FILE):
                prev_alliance = True
                self.root.after(0, self._load_roster)
            time.sleep(0.5)

    def _stop_and_report(self):
        self.monitoring = False
        if self.mitm_process:
            try:
                self.mitm_process.terminate()
                self.mitm_process.wait(timeout=5)
            except Exception:
                try:
                    self.mitm_process.kill()
                except Exception:
                    pass
            self.mitm_process = None

        remove_hosts_entry()
        subprocess.run(["ipconfig", "/flushdns"], capture_output=True,
                       creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))

        self._load_roster()
        self._set_status("Capture stopped — hosts file restored", self.text_dim)
        self.start_btn.configure(state="normal")
        self.stop_btn.configure(state="disabled")
        self.server_entry.configure(state="normal")
        self.detect_btn.configure(state="normal")
        self._generate_report()

    # ── Report Generation ────────────────────────────────────────────────

    def _generate_report(self):
        self._load_roster()
        if not self.clan_members:
            self._write_report(
                "No clan roster available.\n\n"
                "Start capture, log into the game, and the clan\n"
                "roster will be detected automatically.")
            return

        bins = [f for f in glob.glob(os.path.join(SAVE_DIR, "building_*.bin"))
                if not f.endswith("_req.bin")]
        if not bins:
            self._write_report(
                "No building data found.\n\n"
                "Click 'Start Capture', open Raid,\n"
                "and click through each siege building.")
            return

        stats, buildings, bldg_counts = parse_all_buildings(
            SAVE_DIR, self.clan_members)
        self._write_formatted_report(stats, buildings, bldg_counts)
        self.copy_btn.configure(state="normal")

        total = sum(s["scrolls"] for s in stats.values())
        active = sum(1 for s in stats.values() if s["scrolls"] > 0)
        self._set_status(
            f"Report: {len(buildings)} buildings, {total} scrolls, "
            f"{active} active", self.green)

    def _write_formatted_report(self, stats, buildings, bldg_counts):
        self.report_text.configure(state="normal")
        self.report_text.delete("1.0", "end")

        total = sum(s["scrolls"] for s in stats.values())
        wins = sum(s["wins"] for s in stats.values())
        losses = total - wins
        active = sum(1 for s in stats.values() if s["scrolls"] > 0)

        self.report_text.insert("end", "SIEGE SCROLL USAGE REPORT\n", "title")
        self.report_text.insert("end",
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n", "dim")
        self.report_text.insert("end",
            f"Buildings: {len(buildings)}    "
            f"Scrolls: {total} ({wins}W / {losses}L)    "
            f"Active: {active}/{len(stats)}\n\n", "dim")

        hdr = f"  {'#':<4} {'Name':<18} {'Scrolls':>7} {'W':>4} {'L':>4}   Buildings Hit\n"
        self.report_text.insert("end", hdr, "header")
        self.report_text.insert("end",
            f"  {'─'*4} {'─'*18} {'─'*7} {'─'*4} {'─'*4}   {'─'*30}\n", "dim")

        ranked = sorted(stats.values(),
            key=lambda s: (-s["scrolls"], -s["wins"], s["name"].lower()))

        for rank, s in enumerate(ranked, 1):
            bldgs = ", ".join(sorted(s["buildings"])) if s["buildings"] else "-"
            tag = "active" if s["scrolls"] > 0 else "inactive"
            marker = "" if s["scrolls"] > 0 else " ⚠"
            self.report_text.insert("end",
                f"  {rank:<4} {s['name']:<18} {s['scrolls']:>7} "
                f"{s['wins']:>4} {s['losses']:>4}{marker}   {bldgs}\n", tag)

        inactive = [s["name"] for s in ranked if s["scrolls"] == 0]
        if inactive:
            self.report_text.insert("end", "\n")
            self.report_text.insert("end", "INACTIVE (0 scrolls):\n", "header")
            self.report_text.insert("end",
                f"  {', '.join(inactive)}\n", "inactive")

        self.report_text.insert("end", "\n")
        self.report_text.insert("end", "BUILDING BREAKDOWN:\n", "header")
        for bldg, (sc, w) in sorted(bldg_counts.items(), key=lambda x: -x[1][0]):
            ls = sc - w
            ls_str = f" ({ls}L)" if ls else ""
            self.report_text.insert("end",
                f"  {bldg:<22} {sc} scrolls, {w}W{ls_str}\n", "dim")

        self.report_text.configure(state="disabled")

        # Plain text clipboard version
        lines = ["SIEGE SCROLL USAGE REPORT",
                 f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
                 f"Buildings: {len(buildings)}  |  Scrolls: {total} ({wins}W / {losses}L)  |  Active: {active}/{len(stats)}",
                 "",
                 f"  {'#':<4} {'Name':<18} {'Scrolls':>7} {'W':>4} {'L':>4}   Buildings Hit",
                 f"  {'─'*4} {'─'*18} {'─'*7} {'─'*4} {'─'*4}   {'─'*30}"]
        for rank, s in enumerate(ranked, 1):
            bldgs = ", ".join(sorted(s["buildings"])) if s["buildings"] else "-"
            marker = "" if s["scrolls"] > 0 else " ⚠"
            lines.append(
                f"  {rank:<4} {s['name']:<18} {s['scrolls']:>7} "
                f"{s['wins']:>4} {s['losses']:>4}{marker}   {bldgs}")
        if inactive:
            lines.append("")
            lines.append(f"INACTIVE: {', '.join(inactive)}")
        self.report_plain = "\n".join(lines)

    def _copy_report(self):
        if self.report_plain:
            self.root.clipboard_clear()
            self.root.clipboard_append(self.report_plain)
            self._set_status("Copied to clipboard!", self.green)

    def on_close(self):
        self.monitoring = False
        if self.mitm_process:
            try:
                self.mitm_process.terminate()
            except Exception:
                pass
        remove_hosts_entry()
        self.root.destroy()


def main():
    root = tk.Tk()
    app = SiegeTrackerApp(root)
    root.protocol("WM_DELETE_WINDOW", app.on_close)
    root.mainloop()


if __name__ == "__main__":
    main()
